# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Interest.destroy_all
Interest.create(title: 'Photography')
Interest.create(title: 'Film Photography')
Interest.create(title: 'Wedding Photography')
Interest.create(title: 'Styling')
Interest.create(title: 'Food Photography')
Interest.create(title: 'Clothing Photography')
Interest.create(title: 'Analytics')
Interest.create(title: 'Ecommerce Photography')
Interest.create(title: 'Branding')
Interest.create(title: 'Campaign Photography')
Interest.create(title: 'Tech Savy')
Interest.create(title: 'Sports Photography')
Interest.create(title: 'Merchandising')
Interest.create(title: 'Beauty Photography')
Interest.create(title: 'Organization')
Interest.create(title: 'Cosmetic Photography')
Interest.create(title: 'Advertising')
Interest.create(title: 'Event Photography')
Interest.create(title: 'Videography')
Interest.create(title: 'Influencer / Content Creator')
Interest.create(title: 'Animal Photography')
Interest.create(title: 'Hair Stylist')
Interest.create(title: 'Makeup Artist')
Interest.create(title: 'Social Media')
Interest.create(title: 'Content Creator')
Interest.create(title: 'Video Creator')
Interest.create(title: 'Video Editing')
Interest.create(title: 'Picture Editing')
Interest.create(title: 'Video Editor')
Interest.create(title: 'Photoshop')
Interest.create(title: 'Pinterest')
Interest.create(title: 'TikTok')
Interest.create(title: 'YouTube')
Interest.create(title: 'Canva')
Interest.create(title: 'Adobe')
Interest.create(title: 'Microsoft Excel')
Interest.create(title: 'Google Calender')
Interest.create(title: 'Dropbox')
Interest.create(title: 'Google Drive')
Interest.create(title: 'Google Sheets')
Interest.create(title: 'Poshmark')
Interest.create(title: 'Depop')
Interest.create(title: 'Ebay')
